### ISSUE TITLE
I can not run "favorites" example

### ISSUE THREAD

**Issue by point88** [solana-developers/program-examples#103]
When I run basics/favorites/anchor project, there is error like below.
Could you tell me how to fix this?
Thanks in advance

  favorites
Balance: 500,000,000 SOL
    1) Writes our favorites to the blockchain
Invalid arguments: favorites not provided.
    2) Updates the favorites
    3) Rejects transactions from unauthorized signers

  0 passing (301ms)
  3 failing

  1) favorites
       Writes our favorites to the blockchain:
     Error: Invalid arguments: favorites not provided.
      at /home/quan/workspace/favorites/node_modules/@coral-xyz/anchor/src/program/common.ts:50:15
      at Array.forEach (<anonymous>)
      at validateAccounts (node_modules/@coral-xyz/anchor/src/program/common.ts:45:14)
      at ix (node_modules/@coral-xyz/anchor/src/program/namespace/instruction.ts:44:23)
      at txFn (node_modules/@coral-xyz/anchor/src/program/namespace/transaction.ts:24:14)
      at MethodsBuilder.rpc [as _rpcFn] (node_modules/@coral-xyz/anchor/src/program/namespace/rpc.ts:21:18)
      at MethodsBuilder.rpc (node_modules/@coral-xyz/anchor/src/program/namespace/methods.ts:212:17)

  2) favorites
       Updates the favorites:
     Error: null
      at /home/quan/workspace/favorites/tests/favorites.ts:60:13
      at Generator.throw (<anonymous>)
      at rejected (tests/favorites.ts:29:65)

  3) favorites
       Rejects transactions from unauthorized signers:

      AssertionError: expected false to be true
      + expected - actual

      -false
      +true
      
      at /home/quan/workspace/favorites/tests/favorites.ts:75:14
      at Generator.throw (<anonymous>)
      at rejected (tests/favorites.ts:29:65)

**Comment by heyAyushh** [comment]
what’s your node version @point88 ,
also will be great help if you mention solana and anchor versions as well. 

```
node -V
solana -V
anchor -V
```

**Comment by point88** [comment]
Thank you for a reply.
Here is version and code.
[favorites.zip](https://github.com/user-attachments/files/16370722/favorites.zip)
![Screenshot_2](https://github.com/user-attachments/assets/b9b316ee-cb78-4a84-8e0c-d5e7af459a9f)

**Comment by heyAyushh** [comment]
hey @point88, can you use these below versions instead as the project is based on it.

use this as reference https://solana.com/developers/guides/getstarted/setup-local-development

```
anchor version = "0.30.1"
solana version = “1.18.17"
```

**Comment by mikemaccana** [comment]
This hasn't been updated for a month, and he gave a thumbs up, I'm assuming this is handled, let's close.
